### ISSUE TITLE
As a developer, I want to build and implement a CI/CD pipeline for automatic deployment to the server whenever updates are made, ensuring a streamlined update process.

### ISSUE THREAD

**Issue by jonathan-githubofficial** [awaazo/awaazo#254]
### Acceptance Criteria:  
- [x] Backend and Frontend is successfully set up and operational on the PC server at Jonathan Haddad.
- [x] A CI/CD pipeline is established, linked to our repository.
- [x] Any updates in the code triggers automatic deployments to the server.
- [x] Comprehensive pre-deployment checks and post-deployment tests are in place to ensure stable operation.
- [x] Add a DNS to link awaazo.com to our currently hosted website

### Demo Steps:
1. Show how the CI/CD pipeline is integrated with our repository, focusing on the backend directory.
2. Present an automated deployment process, initiated by a repository update.
3. Confirm and validate the codes functionality and stability post-deployment on the server.

### Potential Risks:
- Possible integration hurdles with the existing repository and the CI/CD setup.
- Security risks during the deployment process, requiring stringent safeguards.
- Possible issues getting the domain name (awaazo.com)

### Technical Notes:
- CI/CD pipeline should update on any code change.
- Document every step of the setup and deployment process for clarity and future maintenance.

### added notes:
This item was expanded and changed due to requirement changes. Originally we were going to host this on the concordia servers, but due to limitations around that (needing a VPN to connect, no UI on the device), we changed this to a server that is running in one of our teammates house (@jonathan-githubofficial ). On top of that, we will be hosting both the front and backend on that server for ease of CD/CI as well as no hosting costs

**Comment by BigSaladMan** [comment]
Adding a comment here to document everything that happened with this deployment:

- Originally, this was to be hosted on the concordia servers provided to us. However, upon realizing that we needed a VPN (or be on the concordia network) to connect to any of these servers, we changed this to a PC hosted at one of our teamates house (@jonathan-githubofficial ).
- This means that everything will be hosted there, and connections to that PC remotely will be handled by teamviewer.
-

**Comment by BigSaladMan** [comment]
Everything is currently up and running on his pc, however we still need to connect our domain to his IP:port to be able to access it from awaazo.com

**Comment by BigSaladMan** [comment]
Didnt update this when I finished it, but here is a final rundown:
Front end of the website is currently hosted at [https://alpha.awaazo.com/](https://alpha.awaazo.com/)
Backend is hosted here (for now, this is mostly for testing purposes): [https://dev.awaazo.com/swagger/index.html](https://dev.awaazo.com/)

**Comment by BigSaladMan** [comment]
Risks
1. Possible integration hurdles with the existing repository and the CI/CD setup.
 This ended up being a significant hurdle. The original machines that were provided by concordia ended up being a bust, since we would have only been able to access the website once hosted via vpn or via being on the concordia network.
We thus had to host it on a new machine at our team leaders house as mentionned above.
To finish it off, in order to not expose our team leads IP and keep his network safe, we used a combination of cloudflare and nginx as a reverse proxy in order to keep his ip safe and to port forward in safety.
Conveniently, cloudflare does offer DDOS protection as well on their side, making not be a risk.

2. Security risks during the deployment process, requiring stringent safeguards.
As mentioned above, cloudflare and nginx help abstract away our hosts machines IP. One of the only concerns that currently still exist is the fact that the backend API is not a private one, meaning that anyone who goes to that address can use it. This is a risk that we have to accept, since keeping it open helps massively with testing, but it is something that we will need to change at the final release

3. Possible issues getting the domain name (awaazo.com)
This ended up not being an issue. This domain was available for cheap on cloudflare (~20$-30$), with a year long ownership of that domain

**Comment by BigSaladMan** [comment]
There is more that I didnt add in PRs to this item, since it would expose a LOT of personal configuration information (ex: the entirety of our nginx setup on the PC). 
I will add the deployment script here however since it has relevance to the project: 
[awaazoDeploy.txt](https://github.com/awaazo/awaazo/files/14070851/awaazoDeploy.txt)
Note: this is a .ps1 file, but github does not let you upload them here, thus I simply swapped the extension. simply change it back to make the file work

**Comment by BigSaladMan** [comment]
In order to access this computer, simply contact @jonathan-githubofficial and he can give you access to the teamviewer that we are using when I need access to this computer
