### ISSUE TITLE
As a frontend developer, I want an endpoint to check whether an email exists or not in the database, so I can verify the forgot password form.

### ISSUE THREAD

**Issue by Radwanbaba13** [awaazo/awaazo#301]
## Acceptance Criteria:
- [x] An endpoint is created to check the existence of an email in the database.
- [x] The endpoint returns a response indicating whether the email exists or not.
- [x] The response includes appropriate status codes (e.g., 200 for success, 404 for not found, etc.).
- [x] The endpoint is secure and implements necessary measures to prevent misuse or abuse.
- [ ] Integration tests are implemented to verify the functionality of the endpoint.

## Demo Steps:
1. Send a request to the newly created endpoint with an existing email.
2. Verify that the response indicates the email exists, and the status code is appropriate.
3. Send a request to the endpoint with a non-existing email.
4. Verify that the response indicates the email does not exist, and the status code is appropriate.
5. Test the endpoint with various edge cases, such as invalid email formats.

## Potential Risks:
- [x] Potential exposure of sensitive user data if the endpoint is not properly secured.
- [x] Increased server load due to frequent requests for email existence checks.
- [x] False positives or negatives in email existence checks, impacting user experience.
- [x] Security vulnerabilities if input validation and sanitization are not adequately implemented.

## Technical Notes:
- [x] Implement rate limiting and authentication mechanisms for the email existence endpoint.
- [ ] Ensure that the endpoint is designed to handle concurrent requests efficiently.

**Comment by BigSaladMan** [comment]
Risks:

1.  Potential exposure of sensitive user data if the endpoint is not properly secured.
This has been handled in the implementation of the item.
2.  Increased server load due to frequent requests for email existence checks.
This is a risk that we have to accept for our application. Cloudflare already handles DDOS attacks but in the future we will most likely need a rate limiter/banning IP address if we have such attacks in the future.
3.  False positives or negatives in email existence checks, impacting user experience.
Implementaion prevents this. Only emails that exist in our database can be attempted to get
4.  Security vulnerabilities if input validation and sanitization are not adequately implemented.
Input validation is secure, both with linq on the backend and with the reponse objects from the frontend
